name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/lasania32198/android_kernel_huawei_hi6250-9
          kernel-dir: kernel
          kernel-branch: lineage-20
          config: merge_hi6250_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r383902
          android-version: 12
          anykernel3: false
          bootimg-url: https://pixeldrain.com/api/file/DAU8NFwd?download
