name: CI
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'
      - 'src/*.ts'
      - 'package.json'

  pull_request:
  workflow_dispatch:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Build Kernel
      uses: ./
      with:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/lasania32198/android_kernel_hisilicon_hi6250/
          kernel-dir: hi6250
          kernel-branch: master
          config: merge_hi6250_defconfig
          arch: arm64
          aosp-gcc: true
          android-version: -9.0.0_r30
          disable-lto: true
          anykernel3: true
